title: DS Conference Deadlines
description: Countdowns to Distributed Systems, Performance, and Software Engineering conference deadlines
author: Abhishek Das

domain: "ds-deadlines.github.io"
baseurl: ""

twitter_hashtag: ds-deadlines
github_username: ds-deadlines
github_repo: ds-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
